baseurl = "https://datnguyenduy.github.io/"
languageCode = "en-us"
theme = "hugo-theme-hello-friend"
paginate = 5

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "post"
  # "light" or "dark"
  defaultTheme = "dark"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 2
  # Enable to show reading time in minutes for posts
  showReadingTime = false

[languages]
  [languages.en]
    title = "Hello datdtn"
    subtitle = "Co mot ngay nao do"
    keywords = ""
    copyright = "By Dat"
    menuMore = "Show more"
    writtenBy = "Written by"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    minuteReadingTime = "min read"
    dateFormatSingle = "20023-01-02"
    dateFormatList = "20023-01-02"

    [languages.en.params.logo]
      logoText = "datdtn"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "showcase"
        name = "Showcase"
        url = "/showcase"
        [[languages.en.menu.main]]
        identifier = "test"
        name = "Test"
        url = "/test"
        [[languages.en.menu.main]]
        identifier = "test1"
        name = "Test1"
        url = "/test1"
